# Generated by Django 5.0 on 2023-12-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_doctor_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='d_id',
            field=models.CharField(default='ABC123', max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_id',
            field=models.CharField(default='ABC123', max_length=6, unique=True),
        ),
    ]
