# Generated by Django 4.2.8 on 2023-12-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_doctor_d_id_patient_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='d_id',
            field=models.CharField(default='ABC123', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_id',
            field=models.CharField(default='ABC123', max_length=6, primary_key=True, serialize=False),
        ),
    ]
